#	ROOT FILE

NAME=main
MAINTEX=${NAME}.tex
MAINBIB=${NAME}.bib
MAINHTML=index.tex
HTMLTGT=index.html
#	DIRECTORIES

ROOTDIR=$ROOT
DISSDIR=$ROOT/online
CHAPDIR=$ROOTDIR/chapter
IMGDIR=$ROOTDIR/img
SRCDIR=$ROOTDIR/src
STLDIR=$ROOTDIR/styles
BIBPATH=$ROOTDIR/bibliography
FMTDIR=$ROOTDIR/frontmatter
DBTREE=$IMGDIR/dbtree.jpg
WCFILE=$ROOTDIR/main.csv
GLOSSARY=$ROOTDIR/glossary/
TMPDIR=$ROOTDIR/.tmp
OUTDIR=$ROOTDIR/output
