USAGE="
Usage: $ sh run [OPTIONS]

OPTIONS:
[0] -b --biblio  concatenate <bibliography/*.bib> files into <${NAME}.bib>
[1] -m --concat  concatenate <.tex> files in <content/*.tex> into <${NAME}.tex>
[2] -l --compile compile latex file and output <${NAME}.pdf>
[3] -c --count   count words and output <${NAME}.csv> with more data
[4] -p --pandoc  convert <${NAME}.tex> into html and docx
[5] -t --tidy    place temporary files in <.tmp> and all output in <output>
[6] -r --reset   run updating glossaries (getgloss) and structures (getstruct)
[7] -f --fresh   run updating only structures (getstruct)
[8] -k --backup  backup everything (don't run)
[9] -d --delete  delete temporary files in <.tmp> (don't run)
[10] -h --help    output this help message
[11] -g --compare compare word count between current and backup (or args 1,2)

Utilities:
$ sh getgloss   : download glossary and update <glossary/definitions.tex>
$ sh backup     : backup entire <bin> in <backup/bin_N>
$ sh getstruct  : traverse <chapter> dir for <structure.csv>
$ sh wctex      : sum wordscount of files in arg vector (.tex text only)"


WARNING="Do not edit this file: it was automatically generated from run.sh"

LINE=''